# Generated by Django 4.2.5 on 2023-10-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('ReportID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('WeekStartDate', models.DateField(auto_now_add=True)),
                ('WeekEndDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField()),
                ('Description', models.TextField()),
                ('Assignee', models.CharField(max_length=50)),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccomplishmentID', models.IntegerField()),
                ('Description', models.TextField()),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
    ]
