# Generated by Django 4.2.5 on 2023-10-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('manager_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskToDo',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('assignee', models.CharField(max_length=100)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=200)),
                ('complexity', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('mitigation_plan', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_last_week', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('overall_this_week', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('scope', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('schedule', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('cost', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('overall_health', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.project')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseWiseTimeline',
            fields=[
                ('timeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('assignee', models.CharField(max_length=100)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('revised_end_date', models.DateField()),
                ('status', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=10)),
                ('remark', models.TextField()),
                ('timeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.phasewisetimeline')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=200)),
                ('complexity', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('responsible_party', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dependency_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_completion_date', models.DateField()),
                ('responsible_party', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Assumptions',
            fields=[
                ('assumptions_id', models.AutoField(primary_key=True, serialize=False)),
                ('assumptions', models.TextField()),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('accomplishment_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
    ]
