# Generated by Django 4.2.5 on 2023-10-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='title',
        ),
    ]
