# Generated by Django 4.2.5 on 2023-11-01 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_plan', '0002_remove_weeklyreport_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='title',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='phasewisetimeline',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
