# Generated by Django 4.2.5 on 2023-10-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_plan', '0002_weeklyreport_projectstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseWiseTimeline',
            fields=[
                ('timeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('assignee', models.CharField(max_length=100)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('Phase_name', models.CharField(choices=[('Prepare', 'Prepare'), ('Explore', 'Explore'), ('Realize', 'Realize'), ('Deploy', 'Deploy'), ('Run', 'Run')], max_length=10)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('revised_end_date', models.DateField()),
                ('status', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=10)),
                ('remark', models.TextField()),
                ('timeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.phasewisetimeline')),
            ],
        ),
    ]
