# Generated by Django 4.2.5 on 2023-10-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_plan', '0004_remove_phasewisetimeline_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='Phase_name',
            new_name='phase_name',
        ),
    ]
