# Generated by Django 4.2.5 on 2023-10-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_plan', '0005_rename_phase_name_phase_phase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField()),
                ('Description', models.TextField()),
                ('Assignee', models.CharField(max_length=50)),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_description', models.TextField()),
                ('severity', models.CharField(max_length=200)),
                ('complexity', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('mitigation_plan', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('severity', models.CharField(max_length=200)),
                ('complexity', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('responsible_party', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dependency_id', models.AutoField(primary_key=True, serialize=False)),
                ('dependency_description', models.CharField(max_length=200)),
                ('target_completion_date', models.DateField()),
                ('responsible_party', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('assumption_id', models.AutoField(primary_key=True, serialize=False)),
                ('assumption', models.TextField()),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccomplishmentID', models.IntegerField()),
                ('Description', models.TextField()),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
    ]
