# Generated by Django 4.2.5 on 2023-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Project_manager', 'Project Manager'), ('Management', 'Management')], max_length=20)),
            ],
        ),
    ]
